### ISSUE TITLE
Uncaught TypeError: Cannot read property 'message' of undefined

### ISSUE THREAD

**Issue by PikachuEXE** [DanBrooker/file-icons#160]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.0.2
**System**: Unknown Windows Version
**Thrown From**: [file-icons](https://github.com/DanBrooker/file-icons) package, v1.5.8

### Stack Trace

Uncaught TypeError: Cannot read property 'message' of undefined

```
At D:\portable\Atom\resources\app.asar\node_modules\settings-view\lib\error-view.js:56

TypeError: Cannot read property 'message' of undefined
  at ErrorView.module.exports.ErrorView.initialize (D:\portable\Atom\resources\app.asar\node_modules\settings-view\lib\error-view.js:56:21)
  at ErrorView.View (D:\portable\Atom\resources\app.asar\node_modules\atom-space-pen-views\node_modules\space-pen\lib\space-pen.js:184:25)
  at new ErrorView (D:\portable\Atom\resources\app.asar\node_modules\settings-view\lib\error-view.js:14:46)
  at D:\portable\Atom\resources\app.asar\node_modules\settings-view\lib\install-panel.js:156:44
  at Emitter.module.exports.Emitter.emit (D:\portable\Atom\resources\app.asar\node_modules\event-kit\lib\emitter.js:82:11)
  at PackageManager.module.exports.PackageManager.emitPackageEvent (D:\portable\Atom\resources\app.asar\node_modules\settings-view\lib\package-manager.js:579:27)
  at D:\portable\Atom\resources\app.asar\node_modules\settings-view\lib\package-manager.js:359:17
  at D:\portable\Atom\resources\app.asar\node_modules\settings-view\lib\package-manager.js:384:20
  at exit (D:\portable\Atom\resources\app.asar\node_modules\settings-view\lib\package-manager.js:59:16)
  at triggerExitCallback (D:\portable\Atom\resources\app.asar\src\buffered-process.js:213:47)
  at ChildProcess.<anonymous> (D:\portable\Atom\resources\app.asar\src\buffered-process.js:235:18)
  at emitTwo (events.js:87:13)
  at ChildProcess.emit (events.js:169:7)
  at Process.ChildProcess._handle.onexit (child_process.js:1057:12)

```

### Commands

```
  2x -5:20.7.0 core:confirm (atom-text-editor.editor.mini.is-focused)
  2x -2:01.7.0 core:backspace (atom-text-editor.editor.mini.is-focused)
  2x -1:48.2.0 core:confirm (atom-text-editor.editor.mini.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "atom-html-preview"
    ]
  }
}
```

### Installed Packages

```coffee
# User
file-icons, v1.5.8
file-type-icons, v0.7.0
highlight-line, v0.11.0
highlight-selected, v0.10.1
jsformat, v0.9.0
language-api-blueprint, v1.0.1
minimap, v4.11.2
new-tab, v0.3.0
open-recent, v2.2.4
pigments, v0.8.4
tab-control, v0.6.7
tabs-to-spaces, v0.11.0
trailing-spaces, v0.3.2
travis-ci-status, v0.16.0

# Dev
No dev packages
```

**Comment by DanBrooker** [comment]
Hey, thanks for the bug report. 
But that's not actually enough information for me reproduce the crash.

Have you had it crash more than once? What were you doing at the time?

**Comment by PikachuEXE** [comment]
It's not crashing, just having error message when installing.
It's supposed to display the error message saying something like `it's not compatible with Win32`.
Could be a generic bug for Atom on window, since I got similar problem while installing other packages.

**Comment by DanBrooker** [comment]
Oh right, ok it's probably not from this package then, there's very little code here and nothing to do with a 'message' property

**Comment by PikachuEXE** [comment]
It could be a windows specific problem or installer problem. 
Either way I might just ignore it.
I just copied packages folder from my Mac after that.
Thanks for your time.
