### ISSUE TITLE
Failed to load the fira package

### ISSUE THREAD

**Issue by ganeshkumarsw** [DanBrooker/file-icons#185]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.0.7
**System**: Microsoft Windows 10 Home
**Thrown From**: [file-icons](https://github.com/DanBrooker/file-icons) package, v1.6.9

### Stack Trace

Failed to load the fira package

```
At F:\Embedded\Atom.IO\Fira-master\fira.css:1
(function (exports, require, module, __filename, __dirname) { @font-face{
                                                              ^
Unexpected token ILLEGAL

F:\Embedded\Atom.IO\Fira-master\fira.css:1
(function (exports, require, module, __filename, __dirname) { @font-face{
                                                              ^
SyntaxError: Unexpected token ILLEGAL
  at exports.runInThisContext (vm.js:53:16)
  at Module._compile (module.js:435:25)
  at Object.loadFile [as .js] (C:\Users\GaneshKumar\AppData\Local\atom\app-1.0.7\resources\app.asar\src\babel.js:163:21)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at Package.module.exports.Package.requireMainModule (C:\Users\GaneshKumar\AppData\Local\atom\app-1.0.7\resources\app.asar\src\package.js:759:34)
  at C:\Users\GaneshKumar\AppData\Local\atom\app-1.0.7\resources\app.asar\src\package.js:190:28
  at Package.module.exports.Package.measure (C:\Users\GaneshKumar\AppData\Local\atom\app-1.0.7\resources\app.asar\src\package.js:167:15)
  at Package.module.exports.Package.load (C:\Users\GaneshKumar\AppData\Local\atom\app-1.0.7\resources\app.asar\src\package.js:181:12)
  at PackageManager.module.exports.PackageManager.loadPackage (C:\Users\GaneshKumar\AppData\Local\atom\app-1.0.7\resources\app.asar\src\package-manager.js:405:14)
  at PackageManager.module.exports.PackageManager.loadPackages (C:\Users\GaneshKumar\AppData\Local\atom\app-1.0.7\resources\app.asar\src\package-manager.js:369:14)
  at Atom.module.exports.Atom.startEditorWindow (C:\Users\GaneshKumar\AppData\Local\atom\app-1.0.7\resources\app.asar\src\atom.js:670:21)
  at Object.<anonymous> (C:\Users\GaneshKumar\AppData\Local\atom\app-1.0.7\resources\app.asar\src\window-bootstrap.js:12:8)
  at Object.<anonymous> (C:\Users\GaneshKumar\AppData\Local\atom\app-1.0.7\resources\app.asar\src\window-bootstrap.js:23:4)
  at Module._compile (module.js:452:26)
  at Object.loadFile [as .js] (C:\Users\GaneshKumar\AppData\Local\atom\app-1.0.7\resources\app.asar\src\babel.js:163:21)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at setupWindow (file:///C:/Users/GaneshKumar/AppData/Local/atom/app-1.0.7/resources/app.asar/static/index.js:96:23)
  at window.onload (file:///C:/Users/GaneshKumar/AppData/Local/atom/app-1.0.7/resources/app.asar/static/index.js:36:7)

```

### Commands

```
```

### Config

```json
{
  "core": {}
}
```

### Installed Packages

```coffee
# User
file-icons, v1.6.9
fira, v0.0.0

# Dev
No dev packages
```

**Comment by Alhadis** [comment]
@ganeshkumarsw Has this happened recently?

**Comment by ganeshkumarsw** [comment]
No, seems like it occurred on Aug 2015

**Comment by Alhadis** [comment]
I'll close this for now, since it seems to be a non-issue from what I can tell.

If it happens again, please file another issue and we'll look into it. :-)

**Comment by ganeshkumarsw** [comment]
Ok

On Mon, Feb 29, 2016 at 7:51 AM, John Gardner <notifications@github.com>
wrote:

> I'll close this for now, since it seems to be a non-issue from what I can
> tell.
>
> If it happens again, please file another issue and we'll look into it. :-)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/DanBrooker/file-icons/issues/185#issuecomment-190068454>
> .
>



-- 



Regards,
GaneshKumar.SW



*+919003755682 ganeshkumarsw@gmail.com <ganeshkumarsw@gmail.com>*
<http://www.facebook.com/people/Ganesh-Kumar/1023615437>
