### ISSUE TITLE
Uncaught SyntaxError: Failed to execute 'addColorStop' on 'CanvasGradient': The value provided ('...

### ISSUE THREAD

**Issue by Aotik** [DanBrooker/file-icons#264]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.4.0
**System**: Microsoft Windows 10 Pro
**Thrown From**: [file-icons](https://github.com/DanBrooker/file-icons) package, v1.6.14

### Stack Trace

Uncaught SyntaxError: Failed to execute 'addColorStop' on 'CanvasGradient': The value provided ('hsl(NaN,100%,50%)') could not be parsed as a color.

```
At /C:/Users/natur/.atom/packages/color-picker/lib/extensions/Saturation.coffee:103

Error: Failed to execute 'addColorStop' on 'CanvasGradient': The value provided ('hsl(NaN,100%,50%)') could not be parsed as a color.
    at Error (native)
    at Object._this.canvas.render (file:///C:/Users/natur/.atom/packages/color-picker/lib/extensions/Saturation.coffee:113:35)
    at file:///C:/Users/natur/.atom/packages/color-picker/lib/extensions/Saturation.coffee:129:29
    at Object.emit (file:///C:/Users/natur/.atom/packages/color-picker/lib/modules/Emitter.coffee:11:23)
    at Object.emitColorChanged (file:///C:/Users/natur/.atom/packages/color-picker/lib/extensions/Hue.coffee:32:22)
    at file:///C:/Users/natur/.atom/packages/color-picker/lib/extensions/Hue.coffee:176:47
    at Object.emit (file:///C:/Users/natur/.atom/packages/color-picker/lib/modules/Emitter.coffee:11:23)
    at Object.emitSelectionChanged (file:///C:/Users/natur/.atom/packages/color-picker/lib/extensions/Hue.coffee:26:22)
    at Object._this.control.setSelection (file:///C:/Users/natur/.atom/packages/color-picker/lib/extensions/Hue.coffee:165:36)
    at file:///C:/Users/natur/.atom/packages/color-picker/lib/extensions/Hue.coffee:173:30
    at Object.emit (file:///C:/Users/natur/.atom/packages/color-picker/lib/modules/Emitter.coffee:11:23)
    at Object.emitInputColor (file:///C:/Users/natur/.atom/packages/color-picker/lib/ColorPicker-view.coffee:234:22)
    at Object.open (file:///C:/Users/natur/.atom/packages/color-picker/lib/ColorPicker-view.coffee:311:32)
    at atom-text-editor.<anonymous> (file:///C:/Users/natur/.atom/packages/color-picker/lib/ColorPicker.coffee:42:68)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (C:\Users\natur\AppData\Local\atom\app-1.4.0\resources\app.asar\src\command-registry.js:260:29)
    at CommandRegistry.handleCommandEvent (C:\Users\natur\AppData\Local\atom\app-1.4.0\resources\app.asar\src\command-registry.js:3:61)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (C:\Users\natur\AppData\Local\atom\app-1.4.0\resources\app.asar\src\command-registry.js:160:19)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchContextMenuCommand (C:\Users\natur\AppData\Local\atom\app-1.4.0\resources\app.asar\src\atom-environment.js:1019:28)
    at emitTwo (events.js:87:13)
    at EventEmitter.emit (events.js:172:7)
    at EventEmitter.ipc.sendSync (C:\Users\natur\AppData\Local\atom\app-1.4.0\resources\atom.asar\renderer\api\lib\ipc.js:21:31)
    at BrowserWindow.RemoteMemberFunction [as emit] (C:\Users\natur\AppData\Local\atom\app-1.4.0\resources\atom.asar\renderer\api\lib\remote.js:143:29)
    at ContextMenuManager.module.exports.ContextMenuManager.showForEvent (C:\Users\natur\AppData\Local\atom\app-1.4.0\resources\app.asar\src\context-menu-manager.js:156:33)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentContextmenu (C:\Users\natur\AppData\Local\atom\app-1.4.0\resources\app.asar\src\window-event-handler.js:250:47)
    at HTMLDocument.<anonymous> (C:\Users\natur\AppData\Local\atom\app-1.4.0\resources\app.asar\src\window-event-handler.js:3:61)
```

### Commands

```
     -0:46.5.0 core:copy (atom-text-editor.editor.is-focused)
     -0:45.6.0 core:paste (atom-text-editor.editor.is-focused)
     -0:43.4.0 core:save (atom-text-editor.editor.is-focused.autocomplete-active)
     -0:33.8.0 color-picker:open (atom-text-editor.editor.is-focused)
     -0:28.3.0 editor:consolidate-selections (atom-text-editor.editor.is-focused)
     -0:28.3.0 core:cancel (atom-text-editor.editor.is-focused)
  2x -0:25.3.0 color-picker:open (atom-text-editor.editor.is-focused)
     -0:17.6.0 editor:consolidate-selections (atom-text-editor.editor.is-focused)
     -0:17.6.0 core:cancel (atom-text-editor.editor.is-focused)
     -0:17.4.0 editor:consolidate-selections (atom-text-editor.editor.is-focused)
     -0:17.4.0 core:cancel (atom-text-editor.editor.is-focused)
     -0:17.2.0 editor:consolidate-selections (atom-text-editor.editor.is-focused)
     -0:17.2.0 core:cancel (atom-text-editor.editor.is-focused)
     -0:13.9.0 pane:reopen-closed-item (atom-text-editor.editor.is-focused)
  3x -0:12.9.0 editor:copy-path (atom-text-editor.editor.is-focused)
     -0:02.6.0 color-picker:open (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "autoHideMenuBar": true,
    "disabledPackages": [
      "wrap-guide",
      "multi-wrap-guide"
    ]
  }
}
```

### Installed Packages

```coffee
# User
color-picker, v2.1.0
file-icons, v1.6.14
Stylus, v1.2.1
tabs-to-spaces, v1.0.1
terminal-plus, v0.14.5

# Dev
No dev packages
```

**Comment by Alhadis** [comment]
This actually seems to be related to the colour-picker package, not File Icons. This package doesn't perform any colour modifications in JavaScript (or CoffeeScript, rather). You'd be [better off filing it there](https://github.com/thomaslindstrom/color-picker/issues). =)
