### ISSUE TITLE
Uncaught TypeError: path.replace is not a function

### ISSUE THREAD

**Issue by Eldair** [DanBrooker/file-icons#469]
**Atom Version**: 1.12.7
**Electron Version**: 1.3.13
**System**: Microsoft Windows 10 Home
**Thrown From**: [file-icons](https://github.com/DanBrooker/file-icons) package, v2.0.0

### Stack Trace

Uncaught TypeError: path.replace is not a function

```
At C:\Users\krist\AppData\Local\atom\app-1.12.7\resources\app.asar\node_modules\git-utils\lib\git.js:199

TypeError: path.replace is not a function
    at Repository.relativize (C:\Users\krist\AppData\Local\atom\app-1.12.7\resources\app.asar\node_modules\git-utils\lib\git.js:199:19)
    at GitRepository.module.exports.GitRepository.relativize (C:\Users\krist\AppData\Local\atom\app-1.12.7\resources\app.asar\src\git-repository.js:163:29)
    at GitRepository.module.exports.GitRepository.getCachedPathStatus (C:\Users\krist\AppData\Local\atom\app-1.12.7\resources\app.asar\src\git-repository.js:271:33)
    at File.watchRepo (C:\Users\krist\.atom\packages\file-icons\lib\filesystem\file.js:395:27)
    at new File (C:\Users\krist\.atom\packages\file-icons\lib\filesystem\file.js:31:8)
    at FileRegistry.get (C:\Users\krist\.atom\packages\file-icons\lib\filesystem\file-registry.js:65:17)
    at new Tab (C:\Users\krist\.atom\packages\file-icons\lib\consumers\tab.js:15:32)
    at Tabs.add (C:\Users\krist\.atom\packages\file-icons\lib\consumers\tabs.js:77:16)
    at disposables.UI.delay.onOpenEditor.editor (C:\Users\krist\.atom\packages\file-icons\lib\consumers\tabs.js:25:10)
    at Immediate._ (C:\Users\krist\.atom\packages\file-icons\lib\ui.js:70:38)
    at runCallback (timers.js:574:20)
    at tryOnImmediate (timers.js:554:5)
    at processImmediate [as _immediateCallback] (timers.js:533:5)
```

**Comment by Alhadis** [comment]
Have you reloaded Atom?

**Comment by Eldair** [comment]
Cleared cache & reloaded

**Comment by matheusgrieger** [comment]
Same issue, just installed update.

**Comment by gulrenor** [comment]
Same issue, Win7. Rollback to 1.7.25 still works.

**Comment by Alhadis** [comment]
Ugh, I'm guessing this is related to Windows.

Hang on, gonna chuck a try/catch in there.

**Comment by Alhadis** [comment]
I've published a hotfix. Please let me know if this persists after updating.

I'll have a closer look as to why this is happening.

**Comment by gulrenor** [comment]
Success with 2.0.1

**Comment by Alhadis** [comment]
Thank Christ for that.

**Comment by gluons** [comment]
Oh! So fast. Fix is released before I read this issue 🤣

**Comment by matheusgrieger** [comment]
Yes, solved it!

**Comment by Eldair** [comment]
All good now (:
