### ISSUE TITLE
Uncaught TypeError: Cannot read property 'on' of null

### ISSUE THREAD

**Issue by dmmihaylov** [DanBrooker/file-icons#473]
Hi guys, I get this issue every time I open atom.

**Atom Version**: 1.12.7
**Electron Version**: 1.3.13
**System**: Mac OS X 10.12.2
**Thrown From**: [file-icons](https://github.com/DanBrooker/file-icons) package, v2.0.1

### Stack Trace

Uncaught TypeError: Cannot read property 'on' of null

```
At /Users/dimitarmihaylov/.atom/packages/file-icons/lib/filesystem/resource.js:37

TypeError: Cannot read property 'on' of null
    at TreeEntry.onDidDestroy (/Users/dimitarmihaylov/.atom/packages/file-icons/lib/filesystem/resource.js:37:22)
    at PathStrategy.registerResource (/Users/dimitarmihaylov/.atom/packages/file-icons/lib/service/strategy.js:210:32)
    at PathStrategy.registerResource (/Users/dimitarmihaylov/.atom/packages/file-icons/lib/service/strategies/path-strategy.js:21:12)
    at PathStrategy.check (/Users/dimitarmihaylov/.atom/packages/file-icons/lib/service/strategy.js:133:9)
    at StrategyManager.query (/Users/dimitarmihaylov/.atom/packages/file-icons/lib/service/strategy-manager.js:84:32)
    at Immediate._ (/Users/dimitarmihaylov/.atom/packages/file-icons/lib/service/icon-delegate.js:204:36)
    at runCallback (timers.js:574:20)
    at tryOnImmediate (timers.js:554:5)
    at processImmediate [as _immediateCallback] (timers.js:533:5)
```

### Commands

```
     -0:01.3.0 project-manager:list-projects (atom-pane.pane.active)
     -0:00.7.0 core:move-up (atom-text-editor.editor.mini.is-focused)
     -0:00.3.0 core:confirm (atom-text-editor.editor.mini.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "atom-bootstrap3",
      "aligner",
      "atom-autocomplete-php",
      "minimap",
      "minimap-highlight-selected",
      "symbol-gen",
      "symbols-view"
    ],
    "telemetryConsent": "limited",
    "themes": [
      "nucleus-dark-ui",
      "behave-theme"
    ]
  },
  "file-icons": {
    "onChanges": true
  }
}
```

### Installed Packages

```coffee
# User
aligner, v0.22.3 (inactive)
atom-alignment, v0.12.1 (active)
atom-autocomplete-php, v0.20.2 (inactive)
atom-beautify, v0.29.14 (inactive)
atom-bootstrap3, v1.2.12 (inactive)
atom-codeigniter3-modular-snippets, v0.2.2 (active)
atom-ctags, v5.0.0 (active)
auto-update-packages, v1.0.1 (active)
autoclose-html, v0.23.0 (active)
behave-theme, v1.6.0 (active)
case-conversion, v0.2.0 (inactive)
codeigniter, v0.3.1 (active)
date, v1.1.1 (inactive)
docblock-format-helper, v0.3.0 (active)
docblockr, v0.9.1 (active)
duplicate-removal, v0.1.3 (inactive)
emmet, v2.4.3 (active)
emmet-snippets-compatibility, v1.0.6 (active)
file-icons, v2.0.1 (active)
highlight-selected, v0.11.2 (active)
linter, v1.11.18 (active)
linter-csslint, v1.3.3 (active)
linter-php, v1.3.1 (active)
minimap, v4.25.7 (inactive)
minimap-highlight-selected, v4.4.0 (inactive)
monokai-seti, v0.7.0 (inactive)
nucleus-dark-ui, v0.10.19 (active)
php-cs-fixer, v4.1.0 (active)
pigments, v0.37.0 (active)
project-manager, v3.3.3 (active)
seti-ui, v1.4.0 (inactive)
sort-lines, v0.14.0 (inactive)
symbol-gen, v1.3.1 (inactive)
atom-dark-syntax, v0.27.0 (inactive)
atom-dark-ui, v0.52.0 (inactive)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.45.0 (inactive)
base16-tomorrow-dark-theme, v1.3.0 (inactive)
base16-tomorrow-light-theme, v1.3.0 (inactive)
one-dark-ui, v1.6.2 (inactive)
one-light-ui, v1.6.2 (inactive)
one-dark-syntax, v1.5.0 (inactive)
one-light-syntax, v1.5.0 (inactive)
solarized-dark-syntax, v1.0.5 (inactive)
solarized-light-syntax, v1.0.5 (inactive)
about, v1.7.0 (active)
archive-view, v0.62.0 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.13.1 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.31.4 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (active)
background-tips, v0.26.1 (active)
bookmarks, v0.42.0 (active)
bracket-matcher, v0.82.2 (active)
command-palette, v0.39.0 (inactive)
deprecation-cop, v0.54.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.40.0 (active)
find-and-replace, v0.202.2 (inactive)
fuzzy-finder, v1.4.0 (active)
git-diff, v1.1.0 (active)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.2 (active)
image-view, v0.60.0 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.0 (active)
link, v0.31.2 (inactive)
markdown-preview, v0.158.8 (active)
metrics, v1.1.2 (active)
notifications, v0.65.1 (active)
open-on-github, v1.2.1 (inactive)
package-generator, v1.0.1 (inactive)
settings-view, v0.243.1 (active)
snippets, v1.0.4 (active)
spell-check, v0.68.4 (active)
status-bar, v1.4.1 (active)
styleguide, v0.47.2 (active)
symbols-view, v0.113.1 (inactive)
tabs, v0.103.0 (active)
timecop, v0.33.2 (active)
tree-view, v0.210.0 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.35.1 (active)
whitespace, v0.35.0 (active)
wrap-guide, v0.38.2 (active)
language-c, v0.54.0 (active)
language-clojure, v0.22.1 (active)
language-coffee-script, v0.48.0 (active)
language-csharp, v0.13.0 (active)
language-css, v0.40.1 (active)
language-gfm, v0.88.0 (active)
language-git, v0.15.0 (active)
language-go, v0.43.0 (active)
language-html, v0.47.1 (active)
language-hyperlink, v0.16.1 (active)
language-java, v0.24.0 (active)
language-javascript, v0.122.0 (active)
language-json, v0.18.3 (active)
language-less, v0.29.6 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.37.0 (active)
language-php, v0.37.3 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.1 (active)
language-ruby, v0.70.2 (active)
language-ruby-on-rails, v0.25.1 (active)
language-sass, v0.57.0 (active)
language-shellscript, v0.23.0 (active)
language-source, v0.9.0 (active)
language-sql, v0.25.0 (active)
language-text, v0.7.1 (active)
language-todo, v0.29.1 (active)
language-toml, v0.18.1 (active)
language-xml, v0.34.12 (active)
language-yaml, v0.27.1 (active)

# Dev
No dev packages
```

**Comment by Alhadis** [comment]
Hey mate,

Was the tree-view being displayed when this happened, or was it hidden?

**Comment by dmmihaylov** [comment]
Hi there, tree-view is displayed.

**Comment by Alhadis** [comment]
Does this happen *every* time you open a new Atom window? Or only through the project-manager? This part has me wondering:

```
 -0:01.3.0 project-manager:list-projects (atom-pane.pane.active)
```

Also, are there any non-existent paths in the project-manager? E.g., entries for projects which no longer exist?

**Comment by dmmihaylov** [comment]
I tested couple times and noticed that this error doesn't show up when I initially open Atom and switch between projects. However, the error appears, when I switch again between projects I already opened.

I have four projects, every one of which is correctly configured. Didn't notice any relation between individual project and the error message.

Please let me know if you want me to test something else.

**Comment by Alhadis** [comment]
Hrm, alright. Could you check if `b768acd` solves this?

Just `cd` into a temporary folder, run `git clone https://github.com/DanBrooker/file-icons.git` and then:

```shell
cd /some/temporary/folder
git clone https://github.com/DanBrooker/file-icons.git && cd file-icons
apm install . && apm link -d .
# Then restart Atom in development mode
```

**Comment by dmmihaylov** [comment]
Just did it. No error shows up in dev mode, even after numerous switches between projects. Just for the record, the error shows up in regular mode, but I guess it uses the older version.

**Comment by Alhadis** [comment]
Oh, good to know! If you unlink the cloned package with `apm unlink -d .`, does the error show up again when you restart in development mode?

If so, that confirms it's fixed. Will push out another patch release. =)

**Comment by dmmihaylov** [comment]
Unfortunately, the error shows up again, when I unlinked the package. Here's a screenshot of my dev mode:

https://www.dropbox.com/s/ch2yzoec8nlwrk0/Screenshot%202016-12-29%2023.08.46.jpg?dl=0

Same error, I believe.

**Comment by Alhadis** [comment]
No that's perfect, that's exactly what I needed to know. =) Linking the package with `apm link -d` will only load it when Atom is started in dev-mode, so this confirms that the recent commit fixed it.

Will cut another patch now.

**Comment by Alhadis** [comment]
Okay, done! Please let me know if there are any further issues. =)
