### ISSUE TITLE
Uncaught TypeError: source.onDidExpand is not a function

### ISSUE THREAD

**Issue by fusion809** [DanBrooker/file-icons#478]
Not exactly what triggered this error but I think it's got to do with expanding and collapsing folders in tree view. Here is a screenshot showing the graphical part of the error:

![screenshot_20170101_215247](https://cloud.githubusercontent.com/assets/4717341/21581087/bc4fd256-d06c-11e6-9407-51e59b1a36c8.png)

**Atom Version**: 1.12.7
**Electron Version**: 1.3.13
**System**: "Fedora release 25"
**Thrown From**: [file-icons](https://github.com/DanBrooker/file-icons) package, v2.0.3

### Stack Trace

Uncaught TypeError: source.onDidExpand is not a function

```
At /home/fusion809/.atom/packages/file-icons/lib/consumers/tree-entry.js:32

TypeError: source.onDidExpand is not a function
    at new TreeEntry (/home/fusion809/.atom/packages/file-icons/lib/consumers/tree-entry.js:32:12)
    at TreeView.track (/home/fusion809/.atom/packages/file-icons/lib/consumers/tree-view.js:130:25)
    at resource.onDidFindEntries.entries (/home/fusion809/.atom/packages/file-icons/lib/consumers/tree-view.js:145:64)
    at Function.module.exports.Emitter.simpleDispatch (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:129:28)
    at TreeEntry.scanEntries (/home/fusion809/.atom/packages/file-icons/lib/consumers/tree-entry.js:115:18)
    at TreeEntry.disposables.add.source.onDidAddEntries._ (/home/fusion809/.atom/packages/file-icons/lib/consumers/tree-entry.js:33:37)
    at Function.module.exports.Emitter.simpleDispatch (/usr/share/atom/resources/app.asar/node_modules/atom-keymap/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app.asar/node_modules/atom-keymap/node_modules/event-kit/lib/emitter.js:125:28)
    at Directory.module.exports.Directory.reload (/usr/share/atom/resources/app.asar/node_modules/tree-view/lib/directory.js:370:29)
    at Directory.module.exports.Directory.expand (/usr/share/atom/resources/app.asar/node_modules/tree-view/lib/directory.js:383:12)
    at tree-view-directory.DirectoryView.expand (/usr/share/atom/resources/app.asar/node_modules/tree-view/lib/directory-view.js:178:24)
    at tree-view-directory.DirectoryView.toggleExpansion (/usr/share/atom/resources/app.asar/node_modules/tree-view/lib/directory-view.js:165:21)
    at TreeView.module.exports.TreeView.entryClicked (/usr/share/atom/resources/app.asar/node_modules/tree-view/lib/tree-view.js:468:15)
    at tree-view-directory.<anonymous> (/usr/share/atom/resources/app.asar/node_modules/tree-view/lib/tree-view.js:186:26)
    at space-pen-div.dispatch (/usr/share/atom/resources/app.asar/node_modules/jquery/dist/jquery.js:4435:9)
    at space-pen-div.elemData.handle (/usr/share/atom/resources/app.asar/node_modules/jquery/dist/jquery.js:4121:28)
```

### Commands

```
     -5:51.9.0 core:move-right (atom-text-editor.editor.is-focused)
     -3:27 tree-view:move (span.name.icon.red-hat-icon.dark-red)
     -3:26.8.0 core:move-right (atom-text-editor.editor.mini.is-focused)
     -3:25.9.0 core:move-left (atom-text-editor.editor.mini.is-focused)
     -3:25.6.0 core:move-right (atom-text-editor.editor.mini.is-focused)
     -3:24.6.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -3:22.3.0 tree-view:duplicate (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -1:16.4.0 core:backspace (atom-text-editor.editor.is-focused)
     -1:13.8.0 core:copy (atom-text-editor.editor.is-focused.hyperclick)
     -1:12.4.0 core:move-left (atom-text-editor.editor.is-focused)
     -1:12 core:paste (atom-text-editor.editor.is-focused)
     -1:11.7.0 core:save (atom-text-editor.editor.is-focused)
  2x -0:22.3.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:21.6.0 core:save (atom-text-editor.editor.is-focused)
     -0:06.0 core:select-all (atom-text-editor.editor.is-focused.hyperclick)
     -0:05.6.0 core:copy (atom-text-editor.editor.is-focused.hyperclick)
```

### Config

```json
{
  "core": {
    "customFileTypes": {
      "source.ini": [
        ".buckconfig",
        ".flowconfig"
      ],
      "source.json": [
        ".arcconfig",
        "BUCK.autodeps"
      ],
      "source.octave": [
        "m"
      ],
      "source.python": [
        "BUCK"
      ],
      "source.shell.install": [
        ".install"
      ]
    },
    "disabledPackages": [
      "language-gfm",
      "language-shellscript",
      "exception-reporting",
      "metrics",
      "project-manager",
      "link"
    ],
    "excludeVcsIgnoredPaths": false,
    "projectHome": "/home/fusion809/GitHub/mine",
    "telemetryConsent": "no",
    "themes": [
      "fusion-ui",
      "dark-bint-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
ask-stack, v2.2.0 (inactive)
atom-clang, v1.0.14 (active)
atom-oss-license, v1.1.1 (active)
autocomplete-cmake, v0.3.1 (active)
autocomplete-java, v1.2.5 (inactive)
autocomplete-modules, v1.6.7 (active)
autocomplete-python, v1.8.25 (active)
browser-plus, v0.0.87 (active)
dark-bint-syntax, v0.8.9 (active)
file-icons, v2.0.3 (active)
fusion-ui, v0.12.0 (active)
git-plus, v7.0.4 (active)
git-time-machine, v1.5.4 (inactive)
gpp-compiler, v3.0.7 (active)
hyperclick, v0.0.39 (active)
hyperlink-hyperclick, v1.3.3 (active)
ink, v0.6.2 (active)
julia-client, v0.5.11 (active)
language-ada, v1.1.0 (active)
language-cmake, v0.2.0 (active)
language-d, v3.3.1 (active)
language-debian, v0.2.1 (active)
language-docker, v1.1.7 (active)
language-emacs-lisp, v1.1.1 (active)
language-fsharp, v0.8.4 (active)
language-gfm2, v0.92.2 (active)
language-gnuplot-atom, v0.2.0 (active)
language-haskell, v1.10.4 (active)
language-ini-desktop, v1.18.3 (active)
language-julia, v0.10.0 (active)
language-latex, v1.0.0 (active)
language-liquid, v0.5.1 (active)
language-lua, v0.9.11 (active)
language-matlab-octave, v0.1.2 (active)
language-pascal, v0.18.1 (active)
language-patch2, v1.0.0 (active)
language-qml, v1.0.0 (active)
language-rpm-spec, v0.11.0 (active)
language-rust, v0.4.8 (active)
language-scala, v1.1.8 (active)
language-unix-shell, v0.40.1 (active)
language-vala-modern, v0.3.2 (active)
language-viml, v1.1.3 (active)
latex-completions, v0.3.2 (active)
latex-plus, v0.9.1 (inactive)
linter, v1.11.18 (active)
linter-coffeescript, v1.0.0 (active)
linter-javac, v1.9.4 (active)
linter-js-tenx, v4.0.1 (active)
linter-pylint, v1.2.2 (active)
markdown-writer, v2.6.2 (active)
minimap, v4.25.7 (active)
package-sync, v1.1.0 (active)
pigments, v0.37.0 (active)
script, v3.13.0 (inactive)
terminal-fusion, v2.4.3 (active)
tool-bar, v1.0.1 (active)
toolbar-fusion, v0.8.5 (active)
uber-juno, v0.1.1 (active)
atom-dark-syntax, v0.27.0 (inactive)
atom-dark-ui, v0.52.0 (inactive)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.45.0 (inactive)
base16-tomorrow-dark-theme, v1.3.0 (inactive)
base16-tomorrow-light-theme, v1.3.0 (inactive)
one-dark-ui, v1.6.2 (inactive)
one-light-ui, v1.6.2 (inactive)
one-dark-syntax, v1.5.0 (inactive)
one-light-syntax, v1.5.0 (inactive)
solarized-dark-syntax, v1.0.5 (inactive)
solarized-light-syntax, v1.0.5 (inactive)
about, v1.7.0 (active)
archive-view, v0.62.0 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.13.1 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.31.4 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (active)
background-tips, v0.26.1 (active)
bookmarks, v0.42.0 (active)
bracket-matcher, v0.82.2 (active)
command-palette, v0.39.0 (inactive)
deprecation-cop, v0.54.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.40.0 (inactive)
find-and-replace, v0.202.2 (active)
fuzzy-finder, v1.4.0 (active)
git-diff, v1.1.0 (active)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.2 (active)
image-view, v0.60.0 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.0 (active)
link, v0.31.2 (inactive)
markdown-preview, v0.158.8 (active)
metrics, v1.1.2 (inactive)
notifications, v0.65.1 (active)
open-on-github, v1.2.1 (inactive)
package-generator, v1.0.1 (inactive)
settings-view, v0.243.1 (active)
snippets, v1.0.4 (active)
spell-check, v0.68.4 (active)
status-bar, v1.4.1 (active)
styleguide, v0.47.2 (active)
symbols-view, v0.113.1 (inactive)
tabs, v0.103.0 (active)
timecop, v0.33.2 (active)
tree-view, v0.210.0 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.35.1 (active)
whitespace, v0.35.0 (active)
wrap-guide, v0.38.2 (active)
language-c, v0.54.0 (active)
language-clojure, v0.22.1 (active)
language-coffee-script, v0.48.0 (active)
language-csharp, v0.13.0 (active)
language-css, v0.40.1 (active)
language-gfm, v0.88.0 (inactive)
language-git, v0.15.0 (active)
language-go, v0.43.0 (active)
language-html, v0.47.1 (active)
language-hyperlink, v0.16.1 (active)
language-java, v0.24.0 (active)
language-javascript, v0.122.0 (active)
language-json, v0.18.3 (active)
language-less, v0.29.6 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.37.0 (active)
language-php, v0.37.3 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.1 (active)
language-ruby, v0.70.2 (active)
language-ruby-on-rails, v0.25.1 (active)
language-sass, v0.57.0 (active)
language-shellscript, v0.23.0 (inactive)
language-source, v0.9.0 (active)
language-sql, v0.25.0 (active)
language-text, v0.7.1 (active)
language-todo, v0.29.1 (active)
language-toml, v0.18.1 (active)
language-xml, v0.34.12 (active)
language-yaml, v0.27.1 (active)

# Dev
No dev packages
```

**Comment by Alhadis** [comment]
Odd. Are there any symlinks to directories in the tree-view, perchance?

**Comment by fusion809** [comment]
Just added a screenshot that shows the graphical part of this error. Nope, none of them are symlinks.

**Comment by fusion809** [comment]
The folder name goes off the edge of the tree view (so to see it all you have to horizontally scroll it to the right)

**Comment by fusion809** [comment]
![screenshot_20170101_220206](https://cloud.githubusercontent.com/assets/4717341/21581110/f6613538-d06d-11e6-8d84-0286100e4397.png)

**Comment by Alhadis** [comment]
Anything out of the ordinary when you open this? Is there stuff in the `.errors` array?

```js
console.dir(require(atom.packages.loadedPackages["file-icons"].path + "/lib/log.js"));
```

**Comment by fusion809** [comment]
![screenshot_20170101_221210](https://cloud.githubusercontent.com/assets/4717341/21581147/5d7d71a4-d06f-11e6-94f7-892e9d47bd81.png)

**Comment by Alhadis** [comment]
Ugh, still can't reproduce. @fusion809, could you please clone master locally, and see if ca93b0e fixes this?

After checking, copy me the results of Log's `.error` array one more time, please.

**Comment by fusion809** [comment]
That latest commit seems to have fixed it. It also fixed another minor bug wherein one of my my vim.spec files (and yes this does mean another one of my vim.spec files was assigned this logo without an issue) wasn't given the Red Hat logo.

**Comment by Alhadis** [comment]
Ace, good to know.m 👍 

I'll wait for a day or so before cutting another patch release, just in case there are other bugs reported that need to be addressed. Just keep using your local copy until then. =)
